### PR TITLE
Update data for Konveyor 0.3

### PR DESCRIPTION
**Pull request by mansam**
This PR is intended to update the import data for Konveyor 0.3. The following changes were made:

* `assessments--assessment-risk.json` and `assessments--confidence.json` were removed. These values are calculated on demand by Konveyor 0.3 and are no longer stored.
* The assessments in `assessments.json` were converted from the Pathfinder format to the Konveyor 0.3 format using [mta-assessment-converter](https://github.com/mansam/mta6-assessment-converter).
* `tags` fields removed from TagCategory objects in `tagcategories.json`. The Tag objects in `tags.json` determine the relationship.
* Relationships between objects were cleaned up to remove extraneous fields. The only permitted fields in relationships are `id` and `name`, with `name` being a read-only field. The other fields were being ignored by Konveyor 0.2, but Konveyor 0.3 is strict about input validation and will reject unknown fields.
* Unsupported field `copiedFromReviewID`  removed from Review objects in `reviews.json`.

Requires an updated Tackle import toll which is updated for Konveyor 0.3: https://github.com/konveyor/tackle2-hub/pull/617

### CODE REVIEW

**Comment by danieloh30** [comment]
@wkulhanek can you review and merge this?

**Review by wkulhanek — APPROVED** [review]

**Comment by wkulhanek** [comment]
@danieloh30 will this still work with MTA 6? Or is this MTA 7 only? What tag should the image have? If I just tag as release-0.3 it'll overwrite what's there...

**Comment by danieloh30** [comment]
thx @wkulhanek

**Comment by danieloh30** [comment]
I think this is only for MTA7 so the tag shouldn't be overwritten since the prod is still using MTA 6. Can you revert it and create a new tag for MTA 7?

**Pull request merged**
